export const UPDATE_PROFILE_STARTED = 'UPDATE_PROFILE_STARTED';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export const UPDATE_PROFILE_FINISHED = 'UPDATE_PROFILE_FINISHED';
export const UPDATE_MESSAGE_HIDE = 'UPDATE_MESSAGE_HIDE';
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
export const FORM_CHANGE = '@@redux-form/CHANGE';