export const PASSWORD_UPDATE_STARTED = 'PASSWORD_UPDATE_STARTED';
export const PASSWORD_UPDATE_FAILED = 'PASSWORD_UPDATE_FAILED';
export const PASSWORD_UPDATE_FINISHED = 'PASSWORD_UPDATE_FINISHED';
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
export const FORM_CHANGE = '@@redux-form/CHANGE';