export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_STARTED = 'LOGOUT_STARTED';
export const LOGOUT_FINISHED = 'LOGOUT_FINISHED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';